// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXN-HFDGedCdekiGDCnyMMC-CQd5zx0wo',
    appId: '1:216223062443:web:4ad0050fc35f6dbc9a9aee',
    messagingSenderId: '216223062443',
    projectId: 'events-15e3a',
    authDomain: 'events-15e3a.firebaseapp.com',
    storageBucket: 'events-15e3a.firebasestorage.app',
    measurementId: 'G-7DJ4PZ184S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSgJZAdqnb7Z5ATQzsweW4N04cTcMnSo',
    appId: '1:216223062443:android:dd86716f70c3dd349a9aee',
    messagingSenderId: '216223062443',
    projectId: 'events-15e3a',
    storageBucket: 'events-15e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzT-G8AV1sxkQJ7WzbMcpUbK3yW85I_i4',
    appId: '1:216223062443:ios:c0e68f2fcafc36689a9aee',
    messagingSenderId: '216223062443',
    projectId: 'events-15e3a',
    storageBucket: 'events-15e3a.firebasestorage.app',
    iosBundleId: 'com.example.srlsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzT-G8AV1sxkQJ7WzbMcpUbK3yW85I_i4',
    appId: '1:216223062443:ios:c0e68f2fcafc36689a9aee',
    messagingSenderId: '216223062443',
    projectId: 'events-15e3a',
    storageBucket: 'events-15e3a.firebasestorage.app',
    iosBundleId: 'com.example.srlsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXN-HFDGedCdekiGDCnyMMC-CQd5zx0wo',
    appId: '1:216223062443:web:b8dfa82649947c0b9a9aee',
    messagingSenderId: '216223062443',
    projectId: 'events-15e3a',
    authDomain: 'events-15e3a.firebaseapp.com',
    storageBucket: 'events-15e3a.firebasestorage.app',
    measurementId: 'G-VZXQJ1ZGSB',
  );

}